# Generated by Django 5.1.6 on 2025-08-06 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblcreator',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tblcreator',
            name='email',
            field=models.EmailField(blank=True, max_length=128, null=True),
        ),
    ]
