# Generated by Django 5.1.6 on 2025-08-07 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_tblcreator_dob_alter_tblcreator_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblcreator',
            name='pwd',
        ),
    ]
