# Generated by Django 5.1.6 on 2025-08-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_tblcreator_pwd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auth_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('last_login', models.CharField(max_length=100)),
                ('is_superuser', models.CharField(blank=True, max_length=128, null=True)),
                ('username', models.CharField(blank=True, max_length=128, null=True)),
                ('first_name', models.CharField(blank=True, max_length=128, null=True)),
                ('email', models.EmailField(blank=True, max_length=128, null=True)),
                ('is_staff', models.CharField(blank=True, max_length=128, null=True)),
                ('is_active', models.CharField(blank=True, max_length=128, null=True)),
                ('date_joined', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
    ]
