# Generated by Django 5.1.6 on 2025-08-07 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auth_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Auth_user',
        ),
    ]
