# Generated by Django 5.1.6 on 2025-08-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_delete_auth_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblcreator',
            name='username',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
