# Generated by Django 5.1.6 on 2025-08-07 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_tblcreator_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=255)),
                ('producer', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=100)),
                ('age_rating', models.CharField(max_length=10)),
                ('movie_type', models.CharField(max_length=50)),
                ('video_file', models.FileField(upload_to='videos/')),
            ],
        ),
    ]
