# Generated by Django 5.1.6 on 2025-08-08 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='username',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
