# Generated by Django 5.1.6 on 2025-08-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_video_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='caption',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
