# Generated by Django 5.1.6 on 2025-08-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_video_caption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='caption',
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.FileField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
