# Generated by Django 5.1.6 on 2025-08-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_video_caption_video_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieid', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('mesg', models.CharField(max_length=255)),
            ],
        ),
    ]
