# Generated by Django 5.1.6 on 2025-08-27 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='comment',
            new_name='tblcomment',
        ),
    ]
