# Generated by Django 5.1.6 on 2025-08-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_comment_tblcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblcomment',
            name='rating',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
